# Generated by Django 5.2 on 2025-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quiz_duration_result_total_attempted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='order',
        ),
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.AddField(
            model_name='option',
            name='option_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
