# Generated by Django 5.2 on 2025-04-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_quiz_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, default='Untitled Question', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='questions_set', to='core.option'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_set', to='core.question'),
        ),
    ]
