# Generated by Django 5.2 on 2025-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_option_option_text_alter_quiz_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default='Untitled Question', null=True),
        ),
    ]
