# Generated by Django 5.2 on 2025-04-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_response_student_alter_response_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
